### ISSUE TITLE
Is it inevitable to server to see only 5 tracks

### ISSUE THREAD

**Issue by AlienX97** [askuri/dynmaps#10]
Is it inevitable to server to see only 5 tracks in the records eyepiece widget? Is it possible to show all? I want only that function of this plugin that is letting for adding the all tracsk from speciified folder.

**Comment by askuri** [comment]
This is because records eyepiece gets the tracklist straight from the dedicated server. This plugin makes the server think that there is no more than 5 maps though to enhance performance.
So if records eyepiece should display the correct number of maps, it would have have to get the data from this plugin. That in turn requires writing a mod for records eyepiece, which is (at least for me) unfortunately not going to happen.

What works, is if you simply use the /list command. You can also search for a map with /list searchtext.

@dasschaf Maybe you are interested in writing this mod for records eyepiece?

**Comment by AlienX97** [comment]
Im interested in this plugin cos it lets to add all tracks from one folder, i got arround 650 tracks on the server so i dont need that 5 tracks mod, i would like to see all tracks by records eyepiece and when i write for example 1000 in the cache parameter it scans all maps, i would like to avoid that.

**Comment by askuri** [comment]
Then this plugin is not what you are looking for.
You could check for other plugins or tools like AdminServ (or the good old remoteCP) to do this job for you.

**Comment by dassschaf** [comment]
I can look into fixing records eyepiece for this plugin once I got time, but I think fixing the way more important commands like `admin add/remove/erase` is more important as of now.

However, Askuri is right, for a more practical handling of tracks on a server this plugin isn't what you're looking for.

Edit: Fortunately it's just a few lines that need to be changed, I'll look into that soon:tm:
