### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AlienX97** [askuri/dynmaps#13]
Is it possible to modify trackcount wiget of records eyepiece to show all tracks not just 5? and also does the /admin add commands work?

**Comment by askuri** [comment]
You've opened an issue before, so I assume you might not have the most recent version.
- RE Trackcount widget: should be fixed since #11. If it is not, please let me know. To update the plugin, download this repository again and replace all files in the includes and plugins folder with the respective files in xaseco.
- /admin add: doesn't work according to https://github.com/askuri/dynmaps/issues/6#issuecomment-536321418. Maybe @dassschaf has been thinking about fixing it?

Personally, I currently don't have the capacity to be working on this at all, sorry.

**Comment by dassschaf** [comment]
/admin add *does* work as long the `$tmxdir` variable in `includes/rasp.settings.php` is set right. My bad, I should've updated my comment in #6. 

If you install dynmaps right from the repository the variable is set to `Challenges/dynmaps` already and as such /admin add works out of the box. Admin commands such as add, remove and erase have been fixed with #12.

**Comment by GeraltV47** [comment]
I got another question, if i will use dbtools command /dbtools cleanupdb will i lose all local records? Its me Alien.

**Comment by dassschaf** [comment]
The DBTools plugin compares the tracklist in the server to the tracks present in the database and as such you will probably lose all local records, all karma and all checkpoint times on all tracks that are not currently in the server's tracklist. I haven't tested it, but you definitely shouldn't use that command together with dynmaps.

**Comment by GeraltV47** [comment]
then how to clean up database? will be any plugin compatible with dynmaps for that?

**Comment by askuri** [comment]
There is no plugin specifically developed to work with dynmaps for that purpose. I also checked in the code of dbtools, it is definetely *not* compatible with dynmaps and will lead to data loss.

There is no way for us to make dbtools compatible without updating the plugin itself.

**Comment by GeraltV47** [comment]
So will be a small update of dbtools? Or at least function implemented to dynmaps activated by command? For example /dyn_dbcleanup?

**Comment by askuri** [comment]
I don't have time currently to make a proper of dbtools. However, I quickly took a look again and might have found a quick fix.

This fix is **not tested** and you definitely **need** to **backup** your whole xaseco database and be sure you are able to restore it. Chances are good my fix doesn't work and you lose all your server data if you are unable to restore them. Do it at your own risk. If you are not sure how to backup and restore your database, better don't use dbtools at all (even without my fix).

In case of loss of data, I won't give any support. You have been warned, here we go:

Open plugin.dbtools.php and go to line 1425. Remove these two lines there:
```php
$aseco->client->query('GetChallengeList', 2650, 0);
$serverchallenges = $aseco->client->getResponse();
```

and instead add these two in the same position:
```php
$dyn = new dyn($aseco);
$serverchallenges = $dyn->emulateGetChallengeList();
```

Restart XAseco and execute the cleanup db command as usual.

If you see an error like "undefined class dyn" try adding this line to the beginning of plugin.dbtools.php, just behind <?php:
```php
require 'askuri.dynmaps.php';
```

**Comment by GeraltV47** [comment]
Thank you for advices, i will follow them :smile:

**Comment by GeraltV47** [comment]
But what folder is responsible for my xaseco database? Just that folder i made when i was making the server? In my case, its xaseco_db?

**Comment by askuri** [comment]
The database of Xaseco is always on a MySQL or MariaDB server that you can manage through tools like phpmyadmin. You configured the location of the database in the localdatabase.xml file.

**Comment by GeraltV47** [comment]
I followed these advices and dbtools works good, i even didnt had to add "require 'askuri.dynmaps.php';" dbtools works fine without it.

**Comment by askuri** [comment]
Happy to hear it worked right away.
