### ISSUE TITLE
/admin erase [number] doesn't work

### ISSUE THREAD

**Issue by dassschaf** [askuri/dynmaps#5]
Aseco always spits out the same error trying to remove a track that's not in the current tracklist, but in the /list-list/challenge cache. I think the error is caused because aseco is trying to remove the track from the current tracklist, yet the track is not in the tracklist at that point.
![image](https://user-images.githubusercontent.com/13451345/65821964-d28ecd80-e23c-11e9-9089-509fc3110063.png)

A workaround for now is jukeboxing the track, having it play and then run /admin erasethis, as that is working.

If my assumption is right and the error is caused by the track not being in the actual tracklist, the commands might be better off being modified to /admin erase really deleting the file and /admin remove moving the file into a trash kind of folder in the Tracks directory.

**Comment by askuri** [comment]
That's kinda expected as what DynMaps is actually doing is kind of a bad hack into xaseco.
In fact, all functions in xaseco that use GetChallengeList (or similar) of the server would need to be rewritten because out of the thousands of tracks playable on your server, only a small number (the buffer) is actually known to the server.
I think this should be statet more clearly in the Readme. Could be helpful to have a list of things that certainly do not work. It's not easy though, because third party plug-ins are also affected. For example the records eyepiece tracklist doesn't work for reason mentioned above. 

Feel free to commit improvements in this regard.
